---

- hosts: all
  become: true
  pre_tasks:

  - name: Updating and Upgrading the OS
    apt:
      name: "*"
      state: latest
#      update_cache: true
    when: ansible_distribution == "Ubuntu"

- hosts: controller_node
  become: true
  roles:
    - Neutron
    - Horizon
    - Cinder
